<script>
const rupiah=value=>new Intl.NumberFormat('id-ID',{style:'currency',currency:'IDR',maximumFractionDigits:0}).format(value).replace(/\s/g,' ');
const activate=id=>{document.querySelectorAll('.page').forEach(p=>{p.classList.toggle('active',p.id===id);p.classList.toggle('print',p.id===id&&id==='receipt')});document.querySelectorAll('[data-page-target]').forEach(b=>b.classList.toggle('active',b.dataset.pageTarget===id));history.replaceState(null,'','?page='+id);scrollTo({top:0,behavior:'smooth'})};
document.querySelectorAll('[data-page-target],[data-page-jump]').forEach(b=>b.addEventListener('click',()=>activate(b.dataset.pageTarget||b.dataset.pageJump)));
const cart=new Map,cartList=document.getElementById('cart-list'),cartInputs=document.getElementById('cart-inputs'),empty=document.getElementById('cart-empty'),subtotal=document.getElementById('subtotal'),grand=document.getElementById('grand-total'),paid=document.getElementById('paid'),change=document.getElementById('change');
function renderCart(){if(!cartList)return;cartList.innerHTML='';cartInputs.innerHTML='';let total=0,index=0;cart.forEach(item=>{const line=item.qty*item.price;total+=line;cartList.insertAdjacentHTML('beforeend',`<div class="cart-row"><span class="thumb"><svg width="27" height="32" viewBox="0 0 27 32" fill="none" aria-hidden="true"><path d="M8 5.5h11l.8 4.5c2.15 1.72 3.7 4.82 3.7 8.48v6.77A5.75 5.75 0 0 1 17.75 31h-9.5A5.75 5.75 0 0 1 2.5 25.25v-6.77c0-3.66 1.55-6.76 3.7-8.48L8 5.5Z" fill="#dde1ff" stroke="#00288e" stroke-width="1.4"/><path d="M8.75 1h9.5v5.4h-9.5V1Z" fill="#fff" stroke="#00288e" stroke-width="1.4"/><path d="M5.4 20.5h16.2" stroke="#005074" stroke-width="1.4" stroke-linecap="round"/></svg></span><div class="grow"><strong>${item.name}</strong><span class="muted">${rupiah(item.price)} / ${item.unit} | stok ${item.stock}</span><div class="qty"><button type="button" data-minus="${item.id}">-</button><strong>${item.qty}</strong><button type="button" data-plus="${item.id}">+</button></div></div><span class="price">${rupiah(line)}</span></div>`);cartInputs.insertAdjacentHTML('beforeend',`<input type="hidden" name="items[${index}][product_id]" value="${item.id}"><input type="hidden" name="items[${index}][qty]" value="${item.qty}">`);index++});empty.style.display=cart.size?'none':'block';subtotal.textContent=rupiah(total);grand.textContent=rupiah(total);change.textContent=rupiah(Math.max(0,Number(paid.value||0)-total))}
document.addEventListener('click',e=>{const add=e.target.closest('[data-add-item]'),plus=e.target.closest('[data-plus]'),minus=e.target.closest('[data-minus]');if(add){const id=add.dataset.id,item=cart.get(id)||{id,name:add.dataset.name,price:Number(add.dataset.price),stock:Number(add.dataset.stock),unit:add.dataset.unit,qty:0};if(item.qty<item.stock)item.qty++;cart.set(id,item);renderCart()}if(plus){const item=cart.get(plus.dataset.plus);if(item&&item.qty<item.stock)item.qty++;renderCart()}if(minus){const item=cart.get(minus.dataset.minus);if(item){item.qty--;if(item.qty<1)cart.delete(item.id)}renderCart()}});
paid?.addEventListener('input',renderCart);
document.querySelectorAll('[data-payment-tab]').forEach(tab=>tab.addEventListener('click',()=>{const cash=tab.dataset.paymentTab==='cash';document.querySelectorAll('[data-payment-tab]').forEach(t=>t.classList.toggle('active',t===tab));document.getElementById('payment-type').value=tab.dataset.paymentTab;document.getElementById('cash-fields').style.display=cash?'grid':'none';document.getElementById('transfer-fields').style.display=cash?'none':'grid';if(!cash)paid.value=0;renderCart()}));
document.getElementById('sale-form')?.addEventListener('submit',e=>{if(!cart.size){e.preventDefault();empty.style.display='block'}});
document.getElementById('search-product')?.addEventListener('input',e=>{const q=e.target.value.toLowerCase();document.querySelectorAll('#product-table tbody tr').forEach(r=>r.style.display=r.innerText.toLowerCase().includes(q)?'':'none')});
document.getElementById('search-sale')?.addEventListener('input',e=>{const q=e.target.value.toLowerCase();document.querySelectorAll('#catalog [data-add-item]').forEach(r=>r.style.display=r.innerText.toLowerCase().includes(q)?'grid':'none')});
renderCart();
</script>
