<!DOCTYPE html>
<html lang="id">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Dalwa Water Management System</title>
    <style>
        :root{--bg:#f7f9fb;--surface:#fff;--soft:#f2f4f6;--line:#c4c5d5;--text:#191c1e;--muted:#505f76;--primary:#00288e;--primary2:#1e40af;--psoft:#dde1ff;--green:#047857;--gsoft:#dff7eb;--amber:#b45309;--asoft:#fff3d7;--red:#ba1a1a;--rsoft:#ffdad6;font-family:Inter,ui-sans-serif,system-ui,"Segoe UI",sans-serif}
        *{box-sizing:border-box}body{margin:0;background:var(--bg);color:var(--text)}button,input,select,textarea{font:inherit}button{cursor:pointer}
        .auth{min-height:100vh;display:grid;place-items:center;padding:24px}.login{width:min(430px,100%);background:var(--surface);border:1px solid var(--line);border-radius:8px;padding:28px}.logo{display:flex;align-items:center;gap:12px;margin-bottom:22px}.drop{width:42px;height:42px;border-radius:8px;background:var(--psoft);color:var(--primary);display:grid;place-items:center}.logo h1{font-size:22px;margin:0}.logo p{margin:2px 0 0;color:var(--muted)}
        .shell{min-height:100vh;display:grid;grid-template-columns:270px 1fr}.side{position:sticky;top:0;height:100vh;background:var(--primary2);color:white;display:flex;flex-direction:column}.brand{height:72px;display:flex;align-items:center;gap:12px;padding:0 18px;border-bottom:1px solid rgba(255,255,255,.18)}.brand strong{display:block}.brand span{display:block;color:rgba(255,255,255,.72);font-size:12px}.nav{display:grid;gap:8px;padding:18px 12px}.nav button{border:0;border-radius:8px;background:transparent;color:rgba(255,255,255,.74);display:flex;align-items:center;gap:10px;padding:11px 12px;text-align:left;font-weight:700}.nav button:hover,.nav button.active{background:var(--primary);color:white}.side-foot{margin-top:auto;padding:16px;border-top:1px solid rgba(255,255,255,.18)}.main{min-width:0;padding:28px 32px 44px}.page{display:none}.page.active{display:block}
        h1{font-size:31px;line-height:38px;margin:0 0 6px}h2{font-size:20px;margin:0 0 14px}h3{font-size:16px;margin:0 0 6px}.sub{color:var(--muted);margin:0;line-height:24px}.eyebrow{margin:0 0 4px;color:var(--muted);font-size:12px;text-transform:uppercase;letter-spacing:.08em;font-weight:800}
        .top,.row,.panel-head,.toolbar{display:flex;align-items:center;justify-content:space-between;gap:16px}.top{margin-bottom:22px}.actions{display:flex;gap:8px;flex-wrap:wrap}.btn{min-height:42px;border:1px solid var(--line);border-radius:8px;background:white;color:var(--text);display:inline-flex;align-items:center;justify-content:center;gap:8px;padding:9px 14px;font-weight:800;text-decoration:none}.btn:hover{box-shadow:0 4px 12px rgba(15,23,42,.06)}.btn.primary{background:var(--primary);border-color:var(--primary);color:white}.btn.soft{background:var(--psoft);border-color:transparent;color:var(--primary)}.btn.danger{background:var(--rsoft);border-color:transparent;color:var(--red)}
        .notice{padding:12px 14px;border-radius:8px;margin-bottom:16px}.notice.ok{background:var(--gsoft);color:var(--green)}.notice.err{background:var(--rsoft);color:var(--red)}.grid4{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:16px;margin-bottom:16px}.card,.panel{background:white;border:1px solid var(--line);border-radius:8px}.card{padding:18px}.panel{padding:20px;margin-bottom:16px}.metric{display:flex;align-items:flex-start;justify-content:space-between;margin-bottom:18px}.tile{width:38px;height:38px;border-radius:8px;background:var(--psoft);color:var(--primary);display:grid;place-items:center}.value{font-size:29px;line-height:36px;font-weight:900}.value small{font-size:14px;color:var(--muted);font-weight:600}
        .split{display:grid;grid-template-columns:minmax(0,1fr)380px;gap:16px}.dash{display:grid;grid-template-columns:2fr 1fr;gap:16px}.bars{height:240px;display:grid;grid-template-columns:repeat(7,1fr);gap:10px;align-items:end;border-bottom:1px solid var(--line);padding-top:18px}.bar-wrap{display:grid;gap:8px;text-align:center;color:var(--muted);font-size:12px;font-weight:800;height:100%}.bar{align-self:end;background:var(--psoft);border-radius:6px 6px 0 0;min-height:12px}.bar.current{background:var(--primary)}
        .list{display:grid;gap:10px}.product,.cart-row,.activity{display:flex;align-items:center;gap:12px;border:1px solid transparent;border-radius:8px;padding:11px;background:white}.product:hover,.cart-row{background:var(--soft);border-color:var(--line)}.thumb{width:48px;height:48px;border:1px solid var(--line);border-radius:8px;background:#eef7ff;color:var(--primary);display:grid;place-items:center;flex:0 0 auto}.grow{min-width:0;flex:1}.grow strong{display:block;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.muted{color:var(--muted);font-size:13px}.price{color:var(--primary);font-weight:900;white-space:nowrap}.badge{display:inline-flex;align-items:center;border-radius:999px;padding:4px 8px;font-size:12px;font-weight:800}.badge.green{background:var(--gsoft);color:var(--green)}.badge.amber{background:var(--asoft);color:var(--amber)}.badge.red{background:var(--rsoft);color:var(--red)}.badge.gray{background:var(--soft);color:var(--muted)}
        .table{overflow:auto;border:1px solid var(--line);border-radius:8px}table{width:100%;border-collapse:collapse;min-width:850px}th,td{padding:12px 13px;text-align:left;border-bottom:1px solid var(--line);vertical-align:middle}th{font-size:12px;letter-spacing:.07em;text-transform:uppercase;background:var(--soft);color:var(--muted)}tr:nth-child(even) td{background:#fbfcfd}tr:last-child td{border-bottom:0}
        .form-grid{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:12px}.field{display:grid;gap:6px}label{font-size:13px;font-weight:800;color:var(--muted)}input,select,textarea{width:100%;min-height:42px;border:1px solid var(--line);border-radius:8px;background:white;padding:9px 11px;outline:none}textarea{min-height:88px;resize:vertical}input:focus,select:focus,textarea:focus{border-color:var(--primary);box-shadow:0 0 0 3px rgba(0,40,142,.1)}
        .catalog{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:12px}.catalog button{border:1px solid var(--line);border-radius:8px;background:white;text-align:left;padding:14px;display:grid;gap:10px}.catalog button:hover{border-color:var(--primary);box-shadow:0 4px 12px rgba(15,23,42,.06)}.summary{position:sticky;top:28px;align-self:start}.total{display:flex;justify-content:space-between;padding:10px 0;border-bottom:1px solid var(--line)}.total.big{font-size:22px;font-weight:900;border-bottom:0}.qty{display:flex;gap:6px;align-items:center;margin-top:8px}.qty button{width:28px;height:28px;border:1px solid var(--line);border-radius:6px;background:white;font-weight:900}.tabs{display:grid;grid-template-columns:1fr 1fr;gap:8px;margin:14px 0}.tabs button{border:1px solid var(--line);background:white;border-radius:8px;min-height:42px;font-weight:900}.tabs button.active{border-color:var(--primary);background:var(--psoft);color:var(--primary)}
        .mobile-nav{display:none}.inline-form{display:flex;gap:8px;align-items:center;flex-wrap:wrap}.inline-form input,.inline-form select{width:auto;min-width:112px}.receipt{width:80mm;max-width:100%;margin:auto;background:white;border:1px dashed var(--muted);padding:18px;font-family:"Courier New",monospace}.receipt h3{text-align:center;margin:0 0 4px}.receipt p{text-align:center;margin:0 0 8px}.receipt hr{border:0;border-top:1px dashed #9ca3af;margin:10px 0}.rline{display:flex;justify-content:space-between;gap:12px;margin:5px 0}
        @media(max-width:1180px){.grid4{grid-template-columns:repeat(2,1fr)}.dash,.split{grid-template-columns:1fr}.summary{position:static}.catalog{grid-template-columns:repeat(2,1fr)}.form-grid{grid-template-columns:repeat(2,1fr)}}@media(max-width:820px){.shell{display:block}.side{display:none}.main{padding:18px 16px 92px}.top,.toolbar,.panel-head{align-items:flex-start;flex-direction:column}.grid4,.form-grid,.catalog{grid-template-columns:1fr}.mobile-nav{position:fixed;left:0;right:0;bottom:0;background:white;border-top:1px solid var(--line);display:grid;grid-template-columns:repeat(5,1fr);padding:8px;gap:4px}.mobile-nav button{border:0;border-radius:8px;background:white;color:var(--muted);font-size:11px;font-weight:900;display:grid;place-items:center;gap:3px}.mobile-nav button.active{background:var(--psoft);color:var(--primary)}}@media print{.side,.mobile-nav,.top,.no-print{display:none!important}.shell,.main,.page{display:block;padding:0}.page{display:none}.page.print{display:block}.panel{border:0;padding:0}.receipt{border:0}}
    </style>
</head>
<body>
@php
    $rupiah = fn ($value) => 'Rp '.number_format((int) $value, 0, ',', '.');
    $page = request('page', auth()->check() ? 'dashboard' : 'login');
    $maxChart = max(1, ($salesChart ?? collect())->max('count') ?: 1);
@endphp

@guest
    <main class="auth">
        <section class="login">
            <div class="logo">
                <span class="drop">@include('partials.icon', ['name' => 'dashboard'])</span>
                <div><h1>Dalwa Water</h1><p>Management System</p></div>
            </div>
            @if (isset($errors) && $errors->any()) <div class="notice err">{{ $errors->first() }}</div> @endif
            @if (session('success')) <div class="notice ok">{{ session('success') }}</div> @endif
            <form method="POST" action="{{ route('login') }}" class="list">
                @csrf
                <div class="field"><label for="username">Username</label><input id="username" name="username" value="{{ old('username', 'admin') }}" required autofocus></div>
                <div class="field"><label for="password">Password</label><input id="password" name="password" type="password" value="password" required></div>
                <button class="btn primary" type="submit">@include('partials.icon', ['name' => 'check']) Login</button>
                <p class="sub">Demo awal: <strong>admin/password</strong> atau <strong>kasir/password</strong>.</p>
            </form>
        </section>
    </main>
@else
<div class="shell">
    <aside class="side">
        <div class="brand">
            <span class="drop" style="background:rgba(255,255,255,.14);color:white">@include('partials.icon', ['name' => 'dashboard'])</span>
            <div><strong>Dalwa Water</strong><span>{{ auth()->user()->role === 'admin' ? 'Admin Panel' : 'Kasir POS' }}</span></div>
        </div>
        <nav class="nav">
            <button class="{{ $page === 'dashboard' ? 'active' : '' }}" data-page-target="dashboard">@include('partials.icon', ['name' => 'dashboard']) Dashboard</button>
            <button class="{{ $page === 'inventory' ? 'active' : '' }}" data-page-target="inventory">@include('partials.icon', ['name' => 'box']) Inventory</button>
            @if (auth()->user()->isAdmin())
                <button class="{{ $page === 'stockin' ? 'active' : '' }}" data-page-target="stockin">@include('partials.icon', ['name' => 'truck']) Barang Masuk</button>
            @endif
            <button class="{{ $page === 'pos' ? 'active' : '' }}" data-page-target="pos">@include('partials.icon', ['name' => 'cart']) POS Penjualan</button>
            @if (auth()->user()->isAdmin())
                <button class="{{ $page === 'cashiers' ? 'active' : '' }}" data-page-target="cashiers">@include('partials.icon', ['name' => 'users']) Kasir</button>
                <button class="{{ $page === 'reports' ? 'active' : '' }}" data-page-target="reports">@include('partials.icon', ['name' => 'chart']) Laporan</button>
            @endif
            <button class="{{ $page === 'receipt' ? 'active' : '' }}" data-page-target="receipt">@include('partials.icon', ['name' => 'receipt']) Nota</button>
        </nav>
        <div class="side-foot">
            <strong>{{ auth()->user()->name }}</strong><br><span style="color:rgba(255,255,255,.72)">{{ auth()->user()->username }}</span>
            <form method="POST" action="{{ route('logout') }}" style="margin-top:12px">@csrf<button class="btn" type="submit" style="width:100%">Logout</button></form>
        </div>
    </aside>

    <main class="main">
        @if (session('success')) <div class="notice ok">{{ session('success') }}</div> @endif
        @if (isset($errors) && $errors->any()) <div class="notice err">{{ $errors->first() }}</div> @endif

        <section id="dashboard" class="page {{ $page === 'dashboard' ? 'active' : '' }}">
            <div class="top"><div><p class="eyebrow">Operasional hari ini</p><h1>Overview Penjualan</h1><p class="sub">Monitoring stok, transaksi, pendapatan, dan produk terlaris.</p></div><div class="actions"><button class="btn" type="button">@include('partials.icon', ['name' => 'calendar']) {{ now()->translatedFormat('d M Y') }}</button><button class="btn primary" data-page-jump="pos">@include('partials.icon', ['name' => 'plus']) Transaksi Baru</button></div></div>
            <div class="grid4">
                <article class="card"><div class="metric"><span class="tile">@include('partials.icon', ['name' => 'box'])</span><span class="badge gray">stok</span></div><p class="sub">Total stok</p><div class="value">{{ number_format($stats['total_stock']) }} <small>unit</small></div></article>
                <article class="card"><div class="metric"><span class="tile">@include('partials.icon', ['name' => 'receipt'])</span><span class="badge green">hari ini</span></div><p class="sub">Transaksi</p><div class="value">{{ $stats['today_transactions'] }}</div></article>
                <article class="card"><div class="metric"><span class="tile">@include('partials.icon', ['name' => 'wallet'])</span><span class="badge green">income</span></div><p class="sub">Pendapatan</p><div class="value">{{ $rupiah($stats['today_income']) }}</div></article>
                <article class="card"><div class="metric"><span class="tile">@include('partials.icon', ['name' => 'alert'])</span><span class="badge amber">cek</span></div><p class="sub">Stok rendah</p><div class="value">{{ $stats['low_stock'] }} <small>item</small></div></article>
            </div>
            <div class="dash">
                <section class="panel"><div class="panel-head"><div><h2>Tren Penjualan Mingguan</h2><p class="sub">Jumlah transaksi per hari.</p></div></div><div class="bars">@foreach ($salesChart as $i => $item)<div class="bar-wrap"><div class="bar {{ $loop->last ? 'current' : '' }}" style="height:{{ max(8, $item['count'] / $maxChart * 100) }}%"></div><span>{{ $item['label'] }}<br>{{ $item['count'] }}</span></div>@endforeach</div></section>
                <section class="panel"><h2>Produk Terlaris</h2><div class="list">@forelse ($topProducts as $product)<div class="product"><span class="thumb">@include('partials.product-icon')</span><div class="grow"><strong>{{ $product->nama_barang }}</strong><span class="muted">{{ (int) $product->sold_qty }} terjual</span></div><span class="price">{{ $rupiah($product->harga_jual) }}</span></div>@empty<p class="sub">Belum ada transaksi.</p>@endforelse</div></section>
            </div>
        </section>

        <section id="inventory" class="page {{ $page === 'inventory' ? 'active' : '' }}">
            <div class="top"><div><p class="eyebrow">Master data</p><h1>Manajemen Barang</h1><p class="sub">Kelola produk dan pantau data stok secara terpisah.</p></div></div>
            @if (auth()->user()->isAdmin())
            <section class="panel"><h2>Tambah Produk</h2><form method="POST" action="{{ route('products.store') }}" class="form-grid">@csrf
                <div class="field"><label>Kode</label><input name="kode_barang" required></div><div class="field"><label>Nama</label><input name="nama_barang" required></div><div class="field"><label>Kategori</label><input name="kategori" required></div><div class="field"><label>Satuan</label><input name="satuan" value="Unit" required></div>
                <div class="field"><label>Harga Modal</label><input name="harga_modal" type="number" min="0" required></div><div class="field"><label>Harga Jual</label><input name="harga_jual" type="number" min="0" required></div><div class="field"><label>Stok</label><input name="stok" type="number" min="0" value="0" required></div><div class="field"><label>Status</label><select name="status"><option value="active">Aktif</option><option value="inactive">Nonaktif</option></select></div>
                <button class="btn primary" type="submit">@include('partials.icon', ['name' => 'plus']) Simpan Barang</button>
            </form></section>
            @endif
            <section class="panel"><div class="toolbar" style="margin-bottom:14px"><h2>Data Stok</h2><input id="search-product" placeholder="Cari produk" style="max-width:320px"></div><div class="table"><table id="product-table"><thead><tr><th>Kode</th><th>Nama</th><th>Kategori</th><th>Harga Modal</th><th>Harga Jual</th><th>Stok</th><th>Status</th><th>Aksi</th></tr></thead><tbody>@foreach ($products as $product)<tr><td><strong>{{ $product->kode_barang }}</strong></td><td>{{ $product->nama_barang }}</td><td>{{ $product->kategori }}</td><td>{{ $rupiah($product->harga_modal) }}</td><td class="price">{{ $rupiah($product->harga_jual) }}</td><td>{{ $product->stok }} {{ $product->satuan }}</td><td><span class="badge {{ $product->status === 'active' ? 'green' : 'red' }}">{{ $product->status === 'active' ? 'Aktif' : 'Nonaktif' }}</span></td><td>@if(auth()->user()->isAdmin())<details><summary class="btn soft">@include('partials.icon', ['name' => 'edit']) Edit</summary><form method="POST" action="{{ route('products.update', $product) }}" class="inline-form" style="margin-top:8px">@csrf @method('PUT')<input name="kode_barang" value="{{ $product->kode_barang }}" required><input name="nama_barang" value="{{ $product->nama_barang }}" required><input name="kategori" value="{{ $product->kategori }}" required><input name="harga_modal" type="number" value="{{ $product->harga_modal }}" required><input name="harga_jual" type="number" value="{{ $product->harga_jual }}" required><input name="stok" type="number" value="{{ $product->stok }}" required><input name="satuan" value="{{ $product->satuan }}" required><select name="status"><option value="active" @selected($product->status === 'active')>Aktif</option><option value="inactive" @selected($product->status === 'inactive')>Nonaktif</option></select><button class="btn primary" type="submit">Update</button></form></details><form method="POST" action="{{ route('products.destroy', $product) }}" style="margin-top:8px">@csrf @method('DELETE')<button class="btn danger" type="submit">@include('partials.icon', ['name' => 'trash']) Hapus</button></form>@else<span class="muted">Lihat stok</span>@endif</td></tr>@endforeach</tbody></table></div></section>
        </section>

        @if (auth()->user()->isAdmin())
        <section id="stockin" class="page {{ $page === 'stockin' ? 'active' : '' }}">
            <div class="top"><div><p class="eyebrow">Penambahan stok</p><h1>Barang Masuk</h1><p class="sub">Simpan barang masuk, stok otomatis bertambah.</p></div></div>
            <section class="panel"><form method="POST" action="{{ route('stock-ins.store') }}" class="form-grid">@csrf
                <div class="field"><label>Tanggal</label><input name="tanggal" type="date" value="{{ now()->toDateString() }}" required></div><div class="field"><label>Barang</label><select name="product_id">@foreach($products as $product)<option value="{{ $product->id }}">{{ $product->nama_barang }}</option>@endforeach</select></div><div class="field"><label>Jumlah Masuk</label><input name="qty" type="number" min="1" required></div><div class="field"><label>Supplier</label><input name="supplier" value="Gudang Dalwa"></div><div class="field" style="grid-column:1/-1"><label>Keterangan</label><textarea name="keterangan"></textarea></div><button class="btn primary" type="submit">@include('partials.icon', ['name' => 'check']) Simpan</button>
            </form></section>
            <section class="panel"><h2>Riwayat Barang Masuk</h2><div class="list">@foreach($stockIns as $stock)<div class="activity"><span class="tile">@include('partials.icon', ['name' => 'truck'])</span><div class="grow"><strong>{{ $stock->product->nama_barang }} +{{ $stock->qty }} {{ $stock->product->satuan }}</strong><span class="muted">{{ $stock->supplier }} - {{ $stock->tanggal->format('d/m/Y') }}</span></div><span class="badge green">Masuk</span></div>@endforeach</div></section>
        </section>
        @endif

        <section id="pos" class="page {{ $page === 'pos' ? 'active' : '' }}">
            <div class="top"><div><p class="eyebrow">Kasir</p><h1>Transaksi Penjualan</h1><p class="sub">Pilih barang, input qty, pembayaran, lalu simpan nota.</p></div></div>
            <form method="POST" action="{{ route('transactions.store') }}" id="sale-form" class="split">@csrf
                <section class="panel"><div class="toolbar" style="margin-bottom:14px"><h2>Katalog Produk</h2><input id="search-sale" placeholder="Cari produk" style="max-width:320px"></div><div class="catalog" id="catalog">@foreach($activeProducts as $product)<button type="button" data-add-item data-id="{{ $product->id }}" data-name="{{ $product->nama_barang }}" data-price="{{ $product->harga_jual }}" data-stock="{{ $product->stok }}" data-unit="{{ $product->satuan }}"><span class="thumb">@include('partials.product-icon')</span><div><h3>{{ $product->nama_barang }}</h3><span class="muted">{{ $product->kode_barang }} - stok {{ $product->stok }} {{ $product->satuan }}</span></div><span class="price">{{ $rupiah($product->harga_jual) }}</span></button>@endforeach</div></section>
                <aside class="panel summary"><div class="panel-head"><div><h2>Keranjang</h2><p class="sub">Transaksi baru</p></div><span class="badge green">{{ auth()->user()->name }}</span></div><div id="cart-list" class="list" style="margin:14px 0"></div><div id="cart-empty" class="notice err">Keranjang masih kosong.</div><div id="cart-inputs"></div><div class="total"><span>Subtotal</span><strong id="subtotal">Rp 0</strong></div><div class="total big"><span>Total</span><strong id="grand-total">Rp 0</strong></div><div class="tabs"><button class="active" type="button" data-payment-tab="cash">Tunai</button><button type="button" data-payment-tab="transfer">Transfer</button></div><input type="hidden" name="payment_type" id="payment-type" value="cash"><div id="cash-fields" class="field"><label>Uang Diterima</label><input id="paid" name="uang_diterima" type="number" value="0" min="0"><div class="total big"><span>Kembalian</span><strong id="change">Rp 0</strong></div></div><div id="transfer-fields" class="form-grid" style="grid-template-columns:1fr;display:none"><div class="field"><label>Nama Bank</label><input name="bank_name" value="BSI"></div><div class="field"><label>No Referensi</label><input name="reference_number"></div><div class="field"><label>Status</label><select name="payment_status"><option value="paid">Lunas</option><option value="pending">Pending</option></select></div></div><button class="btn primary" style="width:100%;margin-top:14px" type="submit">@include('partials.icon', ['name' => 'check']) Simpan & Cetak Nota</button></aside>
            </form>
        </section>

        @if (auth()->user()->isAdmin())
        <section id="cashiers" class="page {{ $page === 'cashiers' ? 'active' : '' }}">
            <div class="top"><div><p class="eyebrow">User role</p><h1>Manajemen Kasir</h1><p class="sub">Tambah kasir/admin, aktifkan, dan reset password.</p></div></div>
            <section class="panel"><h2>Tambah User</h2><form method="POST" action="{{ route('cashiers.store') }}" class="form-grid">@csrf <div class="field"><label>Nama</label><input name="name" required></div><div class="field"><label>Username</label><input name="username" required></div><div class="field"><label>Password</label><input name="password" type="password" required></div><div class="field"><label>Role</label><select name="role"><option value="cashier">Kasir</option><option value="admin">Admin</option></select></div><div class="field"><label>Status</label><select name="status"><option value="active">Aktif</option><option value="inactive">Nonaktif</option></select></div><button class="btn primary" type="submit">@include('partials.icon', ['name' => 'plus']) Simpan User</button></form></section>
            <section class="panel"><h2>Daftar User</h2><div class="table"><table><thead><tr><th>Nama</th><th>Username</th><th>Role</th><th>Status</th><th>Penjualan Hari Ini</th><th>Aksi</th></tr></thead><tbody>@foreach($cashiers as $cashier)<tr><td><strong>{{ $cashier->name }}</strong></td><td>{{ $cashier->username }}</td><td>{{ ucfirst($cashier->role) }}</td><td><span class="badge {{ $cashier->status === 'active' ? 'green' : 'red' }}">{{ $cashier->status }}</span></td><td>{{ $rupiah($cashier->today_sales ?? 0) }}</td><td><details><summary class="btn soft">@include('partials.icon', ['name' => 'edit']) Edit</summary><form class="inline-form" method="POST" action="{{ route('cashiers.update', $cashier) }}" style="margin-top:8px">@csrf @method('PUT')<input name="name" value="{{ $cashier->name }}" required><input name="username" value="{{ $cashier->username }}" required><input name="password" type="password" placeholder="Kosongkan jika tetap"><select name="role"><option value="cashier" @selected($cashier->role === 'cashier')>Kasir</option><option value="admin" @selected($cashier->role === 'admin')>Admin</option></select><select name="status"><option value="active" @selected($cashier->status === 'active')>Aktif</option><option value="inactive" @selected($cashier->status === 'inactive')>Nonaktif</option></select><button class="btn primary" type="submit">Update</button></form></details><form class="inline-form" method="POST" action="{{ route('cashiers.reset-password', $cashier) }}" style="margin-top:8px">@csrf @method('PUT')<input name="password" type="password" placeholder="Password baru" required><button class="btn soft" type="submit">@include('partials.icon', ['name' => 'key']) Reset</button></form></td></tr>@endforeach</tbody></table></div></section>
        </section>

        <section id="reports" class="page {{ $page === 'reports' ? 'active' : '' }}">
            <div class="top"><div><p class="eyebrow">Laporan</p><h1>Rekap Penjualan</h1><p class="sub">Laporan harian, bulanan, metode pembayaran, dan export.</p></div><div class="actions"><a class="btn primary" href="{{ route('reports.export-csv') }}">@include('partials.icon', ['name' => 'download']) Export Excel CSV</a></div></div>
            <div class="grid4"><article class="card"><p class="sub">Total transaksi bulan ini</p><div class="value">{{ $stats['month_transactions'] }}</div></article><article class="card"><p class="sub">Pendapatan bulan ini</p><div class="value">{{ $rupiah($stats['month_income']) }}</div></article><article class="card"><p class="sub">Produk terjual</p><div class="value">{{ $stats['month_items'] }}</div></article><article class="card"><p class="sub">Tunai / Transfer</p><div class="value"><small>{{ $rupiah($stats['cash_income']) }} / {{ $rupiah($stats['transfer_income']) }}</small></div></article></div>
            <section class="panel"><h2>Transaksi Terbaru</h2><div class="table"><table><thead><tr><th>No</th><th>Tanggal</th><th>Kasir</th><th>Metode</th><th>Total</th><th>Nota</th></tr></thead><tbody>@foreach($transactions as $transaction)<tr><td>{{ $transaction->kode_transaksi }}</td><td>{{ $transaction->created_at->format('d/m/Y H:i') }}</td><td>{{ $transaction->user->name }}</td><td>{{ $transaction->payment_type }}</td><td class="price">{{ $rupiah($transaction->total) }}</td><td><a class="btn soft" href="{{ route('transactions.receipt', $transaction) }}">Nota</a></td></tr>@endforeach</tbody></table></div></section>
        </section>
        @endif

        <section id="receipt" class="page {{ $page === 'receipt' ? 'active print' : '' }}">
            <div class="top"><div><p class="eyebrow">Nota</p><h1>Nota Terakhir</h1><p class="sub">Buka nota transaksi terakhir atau cetak ulang dari laporan.</p></div><button class="btn" onclick="window.print()" type="button">@include('partials.icon', ['name' => 'print']) Print</button></div>
            <section class="panel">@if($latestTransaction)<div class="receipt"><h3>DALWA WATER</h3><p>Management System<br>Jl. Raya Dalwa, Pasuruan</p><hr><div class="rline"><span>No</span><strong>{{ $latestTransaction->kode_transaksi }}</strong></div><div class="rline"><span>Tanggal</span><span>{{ $latestTransaction->created_at->format('d/m/Y H:i') }}</span></div><div class="rline"><span>Kasir</span><span>{{ $latestTransaction->user->name }}</span></div><hr>@foreach($latestTransaction->details as $detail)<div class="rline"><span>{{ $detail->product->nama_barang }}</span><span>{{ $detail->qty }} x {{ number_format($detail->harga,0,',','.') }}</span></div><div class="rline"><span></span><strong>{{ number_format($detail->subtotal,0,',','.') }}</strong></div>@endforeach<hr><div class="rline"><span>Total</span><strong>{{ number_format($latestTransaction->total,0,',','.') }}</strong></div><div class="rline"><span>Metode</span><span>{{ $latestTransaction->payment_type }}</span></div><div class="rline"><span>Diterima</span><span>{{ number_format($latestTransaction->uang_diterima,0,',','.') }}</span></div><div class="rline"><span>Kembali</span><strong>{{ number_format($latestTransaction->kembalian,0,',','.') }}</strong></div><hr><p>Terima kasih<br>Semoga berkah dan sehat selalu</p></div>@else<p class="sub">Belum ada transaksi.</p>@endif</section>
        </section>
    </main>

    <nav class="mobile-nav">
        <button class="{{ $page === 'dashboard' ? 'active' : '' }}" data-page-target="dashboard">@include('partials.icon', ['name' => 'dashboard']) Dash</button>
        <button class="{{ $page === 'inventory' ? 'active' : '' }}" data-page-target="inventory">@include('partials.icon', ['name' => 'box']) Stok</button>
        <button class="{{ $page === 'pos' ? 'active' : '' }}" data-page-target="pos">@include('partials.icon', ['name' => 'cart']) POS</button>
        @if(auth()->user()->isAdmin())<button class="{{ $page === 'reports' ? 'active' : '' }}" data-page-target="reports">@include('partials.icon', ['name' => 'chart']) Laporan</button>@endif
        <button class="{{ $page === 'receipt' ? 'active' : '' }}" data-page-target="receipt">@include('partials.icon', ['name' => 'receipt']) Nota</button>
    </nav>
</div>

<script>
const rupiah=value=>new Intl.NumberFormat('id-ID',{style:'currency',currency:'IDR',maximumFractionDigits:0}).format(value).replace(/\s/g,' ');
const activate=id=>{document.querySelectorAll('.page').forEach(p=>{p.classList.toggle('active',p.id===id);p.classList.toggle('print',p.id===id&&id==='receipt')});document.querySelectorAll('[data-page-target]').forEach(b=>b.classList.toggle('active',b.dataset.pageTarget===id));history.replaceState(null,'','?page='+id);scrollTo({top:0,behavior:'smooth'})};
document.querySelectorAll('[data-page-target],[data-page-jump]').forEach(b=>b.addEventListener('click',()=>activate(b.dataset.pageTarget||b.dataset.pageJump)));
const cart=new Map,cartList=document.getElementById('cart-list'),cartInputs=document.getElementById('cart-inputs'),empty=document.getElementById('cart-empty'),subtotal=document.getElementById('subtotal'),grand=document.getElementById('grand-total'),paid=document.getElementById('paid'),change=document.getElementById('change');
function renderCart(){if(!cartList)return;cartList.innerHTML='';cartInputs.innerHTML='';let total=0,index=0;cart.forEach(item=>{const line=item.qty*item.price;total+=line;cartList.insertAdjacentHTML('beforeend',`<div class="cart-row"><span class="thumb">@include('partials.product-icon')</span><div class="grow"><strong>${item.name}</strong><span class="muted">${rupiah(item.price)} / ${item.unit} | stok ${item.stock}</span><div class="qty"><button type="button" data-minus="${item.id}">-</button><strong>${item.qty}</strong><button type="button" data-plus="${item.id}">+</button></div></div><span class="price">${rupiah(line)}</span></div>`);cartInputs.insertAdjacentHTML('beforeend',`<input type="hidden" name="items[${index}][product_id]" value="${item.id}"><input type="hidden" name="items[${index}][qty]" value="${item.qty}">`);index++});empty.style.display=cart.size?'none':'block';subtotal.textContent=rupiah(total);grand.textContent=rupiah(total);change.textContent=rupiah(Math.max(0,Number(paid.value||0)-total))}
document.addEventListener('click',e=>{const add=e.target.closest('[data-add-item]'),plus=e.target.closest('[data-plus]'),minus=e.target.closest('[data-minus]');if(add){const id=add.dataset.id,item=cart.get(id)||{id,name:add.dataset.name,price:Number(add.dataset.price),stock:Number(add.dataset.stock),unit:add.dataset.unit,qty:0};if(item.qty<item.stock)item.qty++;cart.set(id,item);renderCart()}if(plus){const item=cart.get(plus.dataset.plus);if(item&&item.qty<item.stock)item.qty++;renderCart()}if(minus){const item=cart.get(minus.dataset.minus);if(item){item.qty--;if(item.qty<1)cart.delete(item.id)}renderCart()}});
paid?.addEventListener('input',renderCart);
document.querySelectorAll('[data-payment-tab]').forEach(tab=>tab.addEventListener('click',()=>{const cash=tab.dataset.paymentTab==='cash';document.querySelectorAll('[data-payment-tab]').forEach(t=>t.classList.toggle('active',t===tab));document.getElementById('payment-type').value=tab.dataset.paymentTab;document.getElementById('cash-fields').style.display=cash?'grid':'none';document.getElementById('transfer-fields').style.display=cash?'none':'grid';if(!cash)paid.value=0;renderCart()}));
document.getElementById('sale-form')?.addEventListener('submit',e=>{if(!cart.size){e.preventDefault();empty.style.display='block'}});
document.getElementById('search-product')?.addEventListener('input',e=>{const q=e.target.value.toLowerCase();document.querySelectorAll('#product-table tbody tr').forEach(r=>r.style.display=r.innerText.toLowerCase().includes(q)?'':'none')});
document.getElementById('search-sale')?.addEventListener('input',e=>{const q=e.target.value.toLowerCase();document.querySelectorAll('#catalog [data-add-item]').forEach(r=>r.style.display=r.innerText.toLowerCase().includes(q)?'grid':'none')});
renderCart();
</script>
@endguest
</body>
</html>
